export const ADD_BOOK = '@ADD_BOOK';
export const ADD_BOOK_SUCCESS = '@ADD_BOOK_SUCCESS';
export const ADD_BOOK_FAILD = '@ADD_BOOK_FAILD';
export const ADD_ONE_BOOK = '@ADD_ONE_BOOK';

export const GET_BOOK = '@GET_BOOK';
export const GET_BOOK_SUCCESS = '@GET_BOOK_SUCCESS';
export const GET_BOOK_FAILD = '@GET_BOOK_FAILD';

export const GET_MY_BOOK = '@GET_MY_BOOK';
export const GET_MY_BOOK_SUCCESS = '@GET_MY_BOOK_SUCCESS';
export const GET_MY_BOOK_FAILD = '@GET_MY_BOOK_FAILD';

export const GET_POPULER_BOOK = '@GET_POPULAR_BOOKS';
export const GET_POPULER_BOOK_SUCCESS = '@GET_POPULAR_BOOKS_SUCCESS';
export const GET_POPULER_BOOK_FAILD = '@GET_POPULAR_BOOKS_FAILD';
